version: "3.8"
services:
  postgres-db:
    image: postgres:15.3
    container_name: teslo-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
  teslo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teslo-app
    restart: always
    ports:
      - 5000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./prisma:/app/prisma
    depends_on:
      - postgres-db